### ISSUE TITLE
working together

### ISSUE THREAD

**Issue by he-yang** [CaptainFerMag/PyADM1#3]
hi 

i am an environmental engineer interested in programming, and am considering to implement activated sludge models in Web-app or Python.

Excited to see that a python implementation of ADM1 has already been done by you, I noted from one of your group publication that you plan to add online-user-interface and also implement ASM in python, may I know your plan on this? Would be interesting if we can work together(for free from my side, for open-source!!!)

**Comment by CaptainFerMag** [comment]
Hi
Thank you very much for your interest. We can discuss it in researchgate or linkedin. Please message me there and I will be happy to discuss. I am going to close this issue here.
