### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by hi124112** [CaptainFerMag/PyADM1#4]
687   flowtemp = {'q_gas' : q_gas, 'q_ch4' : q_ch4}
688   result = pd.concat([gasflow, flowtemp], ignore_index=True)  

TypeError: cannot concatenate object of type '<class 'dict'>'; only Series and DataFrame objs are valid

**Comment by seanrobryan** [comment]
I'm not sure of the exact version of Python and Pandas in which this behavior was changed to cause an error, but it's something I fixed in my fork of the project.
